---
name: Publish Docker Image
on:
  push:
    branches:
      - master
      - dev
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'ScilifelabDataCentre/dds_web'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to Github Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            scilifelabdatacentre/dds-backend
            ghcr.io/scilifelabdatacentre/dds-backend
      - name: Publish image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/backend.Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
